### ISSUE TITLE
Change getAllSubscriptions Request from /add-subscription to /subscriptions/:id Route

### ISSUE THREAD

**Issue by gobrien06** [Jackster001/SubTrack#6]
I'm currently confused by this action in the profileActions. The use-case is for when we are retrieving all the user subscriptions, and from the backend it seems like `/subscriptions/:id` would return all of the user subscriptions.

https://github.com/Jackster001/SubTrack/blob/f9a56398aefbd445c8c58fa6a6e598f79b44dba4/src/Action/profileAction.js#L84-L92

Would it be correct to modify this request to something like this?
` const profile = await axios.get(`${dev}/users/subscriptions/${id}`,{
        headers: { Authorization: localStorage.jwtToken },
    })`

**Comment by Jackster001** [comment]
yes the modification is correct but this action won't be necessary since we
can get all the subscriptions from the profile anyway :)

**Comment by gobrien06** [comment]
Oh, I see! That makes sense, thank you.
